python/django/week4/portfolio/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('resume/', include('resume.urls', namespace='resume')),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('contact/', views.contact, name='contact'),
    path('admin/', admin.site.urls),
]

python/django/week4/resume/urls.py
#Resume url conf

from django.conf.urls import url
from django.urls import path
from . import views
app_name = 'resume'

urlpatterns = [
    path('', views.home, name='home'),
     ]

python/django/week4/resume/models.py
from django.db import models
# Create your models here.

class Resume(models.Model):
    first_name = models.CharField(max_length=64, null=False, blank=False)
    last_name = models.CharField(max_length=64, null=False, blank=False)

    def get_full_name(self):
        """
        returns full name in the form - firstname lastname
        """
        return "{} {}".format(self.first_name,self.last_name)

    def get_last_name_first_name(self):
        """
        returns full name in the form - lastname, firstname
        """
        return "{}, {}".format(self.last_name,self.first_name)

    def get_experience(self):
        """
        returns all the fields in the Experience model
        """
        return self.experience_set.all()

    def get_education(self):
        """
        returns all the fields in the Education model
        """
        return self.education_set.all()

class Experience(models.Model):
    """
    resume is the Foreign key
    """
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=64, null=False, blank=False)
    location = models.CharField(max_length=64, null=False, blank=False)
    start_date = models.DateField()
    end_date = models.DateField()
    description = models.CharField(max_length=255, null=False, blank=True)

    def __str__(self):
        return self.title

class Education(models.Model):
    """
    resume is the Foreign key
    """
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, default=1)
    institution_name = models.CharField(max_length=64, null=False, blank=False)
    location = models.CharField(max_length=64, null=False, blank=False)
    degree = models.CharField(max_length=255, null=False, blank=False)
    major = models.CharField(max_length=255, null=False, blank=False)
    gpa = models.FloatField(null = False, blank = False)

    def __str__(self):
        return self.institution_name

python/django/week4/portfolio/views.py
from django.shortcuts import render

def home(request):
    '''
    Renders a home page
    '''
    return render(request, 'home.html', context=None)

def portfolio(request):
    '''
    Renders a portfolio page
    '''
    return render(request, 'portfolio.html', context=None)

def resume(request):
    '''
    Renders a resume page
    '''
    return render(request, 'resume.html', context=None)

def contact(request):
    '''
    Renders a contact page
    '''
    return render(request, 'contact.html', context=None)       

python/django/week4/resume/views.py
from django.shortcuts import render
from .models import Experience, Education, Resume

# Create your views here.
def home(request):
    """
    Renders the Resume app home template
    """
    resume_qs = Resume.objects.first()
    context = {'res': resume_qs}
    return render(request, 'resume/home.html', context)

python/django/week4/resume/templates/resume/home.html
{% extends 'base.html' %}

{% block content %}

<!---For Experience Model--->
{% if res %}

<H1 style="color:blue;"> Personal Information </H1>
<TABLE>
    <TR>
        <TD>{{res.get_full_name}}</TD>
    </TR>
</TABLE>

{% else %}

<h1>No Data Found! Contact an Admin!</h1>
{% endif %}

<!---For Experience Model--->
{% if res %}

<H1 style="color:blue;"> Work Experience </H1>
{% for exp_new in res.get_experience %}
<TABLE>
    <TR>
        <TD>{{exp_new.title}}</TD>
        <TD>{{exp_new.location}}</TD>
        <TD>{{exp_new.start_date}}</TD>
        <TD>{{exp_new.end_date}}</TD>
        <TD>{{exp_new.description}}</TD>
    </TR>
</TABLE>

{% endfor %}
{% else %}

<h1>No Data Found! Contact an Admin!</h1>
{% endif %}

<!---For Education Model--->

{% if res %}

<H1 style="color:blue;"> Education </H1>
{% for edu_new in res.get_education %}
<TABLE>
    <TR>
        <TD>{{edu_new.institution_name}}</TD>
        <TD>{{edu_new.location}}</TD>
        <TD>{{edu_new.degree}}</TD>
        <TD>{{edu_new.major}}</TD>
        <TD>{{edu_new.gpa}}</TD>
    </TR>
</TABLE>
<!---table--->
{% endfor %}
{% else %}

<h1>No Data Found! Contact an Admin!</h1>
{% endif %}

{% endblock %}

python/django/week4/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Swechchha's Portfolio</title>
    <link rel='stylesheet' href="{% static 'css/style.css' %}" />
  </head>
  <body>
      <nav>
        <a href="{% url 'home' %}">Home</a> |
        <a href="{% url 'portfolio' %}">Portfolio</a> |
        <a href="{% url 'resume:home' %}">Resume</a> |
        <a href="{% url 'contact' %}">Contact</a>

      </nav>

      {% block content %}
      {% endblock %}

  </body>
</html>

python/django/week4/templates/contact.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <form id="contact" action="" method="post">
    <br>
      <fieldset>
       <legend>Quick Contact</legend>
        First name:<br>
        <input type="text" name="firstname" ><br>
        Last name:<br>
        <input type="text" name="lastname" ><br>
        Contact Number:<br>
        <input type="text" name="contact number" ><br>
        Email:<br>
        <input type="text" name="contact number" ><br>
        Message:<br>
        <textarea placeholder="Type your Message Here...." tabindex="0">
        </textarea><br>
        <br>
        <input type="submit" value="Submit">
      </fieldset>
    </form>
</div>

{% endblock %}

python/django/week4/templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class='homepage-content'>
  <div class='homepage-banner'>
    <h1 style="color:blue;">This is Swechchha's Portfolio!</h1>
  </div>
</div>


{% endblock %}

python/django/week4/templates/portfolio.html
{% extends 'base.html' %}
{% block content %}
<div id="header">
   <h3 style="color:blue;"> Projects I worked on! </h3>
   <div class="left">
      <div class="right">
         <ul>
            <h4>1. Client- ZF India</h4>
            <li>Developed ALV reports and Smartforms in SAP ABAP.</li>
            <li>Customized Infotypes and Tables creation and Created Function modules.</li>
            <li>Enhanced standard Infotypes as per the client requirements. </li>
            <li>Coding and Creation of Unit Test Plans (UTP) for the objects. </li>
            <h4>2. Client- AL ELM Saudi Arabia</h4>
            <li>Developed and modified Dialog programming using Screen Painter and Menu Painter and table control and Multiple Screen dialogue.
            <li>Created custom infotype of type PA with subtypes and assigned default values, Validations.</li>
            <li>Creation of Unit Test Plans (UTP) for the objects.</li>
            <h4>3. Client- Amgen USA</h4>
            <li>Worked on SAP to Workday Conversion in this project.</li>
            <li>Created custom infotype of type PA with subtypes as per the client requirements</li>
            <li>Development of Interfaces for transmission of data from SAP to Workday- created, IDOC, LSMW, function modules.</li>
            <li>Creation of Unit Test Plans, Code review check documents for the objects. </li>
         </ul>
      </div>
   </div>
</div>
{% endblock %}

python/django/week4/templates/resume.html
{% extends 'base.html' %}

{% block content %}

<div id="header">
	<p id="name">
		<b>Swechchha Tiwari</b>
	</p>
	<a href="mailto:swechchhatiwari@gmail.com">
		<p id="email">swechchhatiwari@gmail.com</p>
	</a>
</div>
<div class="left"></div>
<div class="right">
	<h4>Objective</h4>
	<p>A position where there is a need for an individual with technical skills in the industry where my skills can be used effectively and productively.</p>
	<h4>Experience</h4>
	<p>Skilled software professional with 3 years of experience in SAP ABAP (ABAP HR) with a proven track record of company and customer satisfaction.</p>
	<ul>
		<li>SAP certified development associate – ABAP with SAP NetWeaver 7.02</li>
		<li>Developed ALV reports, Smartforms, Interfaces and Enhancements in SAP ABAP.</li>
		<li>Interaction with functional consultants to understand functional requirement and preparing technical specification.</li>
		<li>Skills in Debugging, Runtime Analysis, Performance Tuning, Code Inspector and Extended Program Check for better performance. </li>
	</ul>
	<h4>Skills</h4>
	<p>Languages: ABAP/4, JAVA, ASP.NET, C#, C, C++,Python</p>
	<p>Database:SQL Server 2014/2008/2005, MySQL, PostgreSQL</p>
	<h4>Education</h4>
	<p>BE, Information Technology, RGPV University, India</p>
	<ul>
		<li>GPA: 3.8</li>
	</ul>
</div>
<div id="footer">
	<h4>Address</h4>
	<p> 11 Borough rd APT 1130, Penacook | Tel: +1 (603) 417-9797</p>
</div>

{% endblock %}